# Generated by Django 4.1 on 2022-08-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportsAvailableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.IntegerField()),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='flights.airportsavailablemodel')),
                ('Origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='flights.airportsavailablemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('flight', models.ManyToManyField(blank=True, related_name='passenger', to='flights.flightsearchmodel')),
            ],
        ),
    ]
